### ISSUE TITLE
Mounting volumes into docker image

### ISSUE THREAD

**Issue by goramartin** [martaannaj/RecommenderServer#77]
Hello,
sorry for interrupting again. I am trying to mount volume with precomputed schema tree data structure.
I am encountering error while loading the format.

Output:
```
[+] Running 1/1
 ✔ Container recommenderserver-wdrec-1  Recreated                                                                                                      0.1s
Attaching to recommenderserver-wdrec-1
recommenderserver-wdrec-1  | Starting RecommenderServer...
recommenderserver-wdrec-1  | 2023/11/27 20:05:26 Loading schema (from file testdata/latest-truthy-item-filtered-sorted.nt.gz.schemaTree.typed.bin):
recommenderserver-wdrec-1  | 2023/11/27 20:05:26 Start loading schema (protocol buffer format)
recommenderserver-wdrec-1  | 2023/11/27 20:05:26 proto: cannot parse invalid wire-format data
recommenderserver-wdrec-1  | panic: proto: cannot parse invalid wire-format data
recommenderserver-wdrec-1  |
recommenderserver-wdrec-1  |
recommenderserver-wdrec-1  | goroutine 1 [running]:
recommenderserver-wdrec-1  | log.Panicln({0xc0000f9cc0?, 0xc0000145d0?, 0x0?})
recommenderserver-wdrec-1  |    /usr/lib/go-1.19/src/log/log.go:402 +0x65
recommenderserver-wdrec-1  | RecommenderServer/cli.CommandWikiServe.func1(0xc000b82300?, {0xc0001eee70?, 0x3?, 0x3?})
recommenderserver-wdrec-1  |    /srv/recommender/cli/serve.go:56 +0x28b
recommenderserver-wdrec-1  | github.com/spf13/cobra.(*Command).execute(0xc000b82300, {0xc0001eee10, 0x3, 0x3})
recommenderserver-wdrec-1  |    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
recommenderserver-wdrec-1  |    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
recommenderserver-wdrec-1  | github.com/spf13/cobra.(*Command).ExecuteC(0xc000b82000)
recommenderserver-wdrec-1  |    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
recommenderserver-wdrec-1  | github.com/spf13/cobra.(*Command).Execute(...)
recommenderserver-wdrec-1  |    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
recommenderserver-wdrec-1  | main.main()
recommenderserver-wdrec-1  |    /srv/recommender/main.go:127 +0x3fa
recommenderserver-wdrec-1 exited with code 2
```

My docker compose:
```
version: '3.8'
services:
  wdrec:
    image: recommenderserver:latest
    restart: "no"
    command: ./RecommenderServer serve --hard_limit -1 /latest-all.json.bz2.schemaTree.typed.pb
    volumes:
      - /home/gora/recinput/latest-all.json.bz2.schemaTree.typed.pb:/latest-all.json.bz2.schemaTree.typed.pb:ro
    expose:
      - "8771"
    ports:
      - "8771:8771"
```
I tried separately making a different docker compose file with the base of official golang 1.20, which works and running exe file directly works as well. Maybe it is the volume itself and it reads different file.
I was wondering would it be possible to provide a folder in the image where I could try to bind volumes? The problems with volumes usually are that that require absolute path. That results in  a problem since I do not now the image's internal structure.
